<!DOCTYPE html>
<html style="background-color: #1f2b3b">
<head>
    <title>Регистрация</title>
</head>
<body>
        <nav class="navbar navbar-dark justify-content-between" style="background-color: #2e5179;">
            <a  class="navbar-brand">
            <h1>
            <p class="text-light">
            <img src="/public/img/Call.png" width="50" height="50" alt="">
            Cправочник</p></h1></a>
        </form>
        </nav>  
	<div class="container-fluid" style="background-color: #1f2b3b">
    <?php echo $this->tag->form("signup/register"); ?>
    <br>
	<br>
    	  <div class="form-group">
    	  	<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: #2e5179; ">
    	  	<h1 class="text-center"><a class="text-white">Регистрация </a></h1>
            <p><?php $this->flash->output() ?></p>
    		  <label for="email"><a class="text-white">Логин </a></label>

    		 <?php
               if(empty($name)) {
                echo '<input type="text" class="form-control" id="name" placeholder="Введите логин"  name="name"> ';
            }
             else{
                echo '<input type="text" class="form-control  is-invalid " id="name" placeholder="Введите логин"  name="name"> ';
             } ?>
               <p class="text-danger"><?php if(empty($name)==false){echo $name;} ?></p>
    	    </div>
    	  </div>
    	  	
			<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: #2e5179">
    		  <label for="email"><a class="text-white">Email адрес </a></label>

    		 <?php
               if(empty($email) ){
              echo '<input type="email" class="form-control" id="email" placeholder="Введите email"  name="email">';
          }else{
            echo '<input type="email" class="form-control  is-invalid" id="email" placeholder="Введите email"  name="email">';
          } ?>
          <p class="text-danger"><?php if(empty($email)==false){echo $email;} ?></p>
    		
			</div>
			</div>
			<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: #2e5179">
    		  <label for="password"><a class="text-white">Пароль</a></label>

              <?php 
              if(empty($password) ){
               echo '<input type="password" class="form-control" id="password" placeholder="Введите пароль" name="password">';
              }else{
                echo '<input type="password" class="form-control  is-invalid" id="password" placeholder="Введите пароль" name="password">';
              }
              ?>
              <p class="text-danger"><?php if(empty($password)==false){echo $password;} ?></p>


              </div>
            </div>
            <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4" style="background-color: #2e5179">
              <label for="confirmPassword"><a class="text-white">Повторите пароль </a></label>

              <?php 
              if( empty($confirmPassword) ){
              echo  '<input type="Password" class="form-control" id="confirmPassword" placeholder="Повторите пароль" name="confirmPassword">';
          }else{
            echo  '<input type="Password" class="form-control  is-invalid" id="confirmPassword" placeholder="Повторите пароль" name="confirmPassword">';
          } 
          ?>
          <p class="text-danger"><?php if(empty($confirmPassword)==false ){echo $confirmPassword;} ?></p>
    		  
    		  <br>
    		  <?php echo $this->tag->submitButton(["Регистрация", 'class' => 'btn btn-secondary btn-block','style' =>'border: 2px solid black']); ?>
    		  </form>
    		  <br>
				<?php echo $this->tag->linkTo(["index", "Назад", 'class' => 'btn btn-secondary btn-block','style' =>'border: 2px solid black']); ?>
    		  <br>
    	    </div>
    	  </div>
    	  </div>
    	</div>
    	</div>
    </div>
</body>